version: "3"
services:
  web:
    image: nginx:latest
    container_name: huobi-web
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./:/usr/share/nginx/html
      - ./log:/var/log/nginx
      - ./nginx:/etc/nginx/conf.d

